name: Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

concurrency:
  group: {% raw %}${{ github.workflow }}-${{ github.ref }}{% endraw %}
  cancel-in-progress: true

jobs:
  build:
    runs-on: {% raw %}${{ matrix.os }}{% endraw %}
    permissions:
      contents: read
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python {% raw %}${{ matrix.python-version }}{% endraw %}
      uses: actions/setup-python@v5
      with:
        python-version: {% raw %}${{ matrix.python-version }}{% endraw %}
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: Install dependencies
      run: uv sync -v
    - name: Lint
      run: uv run ruff check --output-format=github .
    - name: Format
      run: uv run black --check --diff .
    - name: Run coverage
      run: uv run coverage run -m pytest
    - name: Generate coverage report
      run: uv run coverage report --format=markdown > coverage.md
    - name: Publish coverage to summary
      run: cat coverage.md >> $GITHUB_STEP_SUMMARY
      shell: bash
