name: Build

env:
  NEW_COOKIE_REPO: example_python_project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Configure git
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
    - run: pipx install cookiecutter
    - name: Cut cookies
      run: cookiecutter --no-input --overwrite-if-exists .
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - run: uv lock
      working-directory: ${{ env.NEW_COOKIE_REPO }}
    - name: Install dependencies
      run: uv sync
      working-directory: ${{ env.NEW_COOKIE_REPO }}
    - name: Run unit-tests
      run: uv run pytest
      working-directory: ${{ env.NEW_COOKIE_REPO }}
    - name: Lint ruff
      run: uv run ruff check .
      working-directory: ${{ env.NEW_COOKIE_REPO }}
