name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:


jobs:
  build:
    runs-on: {{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - run: pipx install cookiecutter
    - name: Cut cookies
      run: cookiecutter --no-input --overwrite-if-exists .
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi  
        cd example_python_project       
        python -m pip install ".[dev]"  # install package + test dependencies
    - name: About
      run: |
        cd example_python_project 
        python -m example_python_project.about
    - name: Test with pytest
      run: |
        cd example_python_project 
        python -m pytest --cov --cov-fail-under 100 
    - name: Lint ruff
      run: |
        python -m ruff check example_python_project hooks        
    - name: Typecheck with mypy
      run: |
        cd example_python_project 
        python -m mypy example_python_project 
    - name: Build documentation with sphinx
      run: |
        cd example_python_project
        sphinx-build -M html docsrc docsrc/_build
