name: Build

env:
  NEW_COOKIE_REPO: example_python_project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Configure git
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - run: uv venv && uv pip sync requirements.txt
    - name: Cut cookies
      run: uv run cookiecutter --no-input --overwrite-if-exists .
    - name: Install dependencies
      run: uv sync -v
      working-directory: ${{ env.NEW_COOKIE_REPO }}
    - run: uv run pre-commit run -a
      working-directory: ${{ env.NEW_COOKIE_REPO }}
    - name: Run coverage
      run: uv run coverage run -m pytest
      working-directory: ${{ env.NEW_COOKIE_REPO }}
    - name: Generate coverage report
      run: uv run coverage report --format=markdown > coverage.md
      working-directory: ${{ env.NEW_COOKIE_REPO }}
    - name: Publish coverage to summary
      run: cat coverage.md >> $GITHUB_STEP_SUMMARY
      working-directory: ${{ env.NEW_COOKIE_REPO }}
      shell: bash
